on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create GH Release and upload to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python for PyPI Release
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies for PyPI Release
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build artifacts
        run: python setup.py sdist bdist_wheel
      - name: Create GH Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: latest_release_notes.md
          artifacts: "dist/*"
      - name: Upload to pypi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
