name: Merge develop, run tests and build documentation

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop, master]
  workflow_dispatch:
    inputs:
      reason:
        description: Why did you trigger the pipeline?
        required: False
        default: Check if it runs again due to external changes

jobs:
  build:
    runs-on: ubuntu-latest
    # This is needed to enable host name resolution for the minio service from the tests
    #https://docs.github.com/en/actions/using-containerized-services/about-service-containers#mapping-docker-host-and-service-container-ports
    # https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers#running-jobs-in-containers
    container: python:3.8-slim-buster
    services:
      remote-storage:
        image: bitnami/minio:latest
        ports:
        - "9000:9000"
        - "9001:9001"
        env:
          MINIO_ROOT_USER: minio-root-user
          MINIO_ROOT_PASSWORD: minio-root-password

    steps:
      # pandoc needed for docu, see https://nbsphinx.readthedocs.io/en/0.7.1/installation.html?highlight=pandoc#pandoc
      - name: Install Non-Python Packages
        run: apt-get update -yq && apt-get -yq install pandoc git git-lfs rsync
      - name: Safe directory workaround
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false
      # lfs=true is not enough, see https://stackoverflow.com/questions/61463578/github-actions-actions-checkoutv2-lfs-true-flag-not-converting-pointers-to-act
      - name: Checkout LFS Objects
        run: git lfs pull
      - name: Merge develop into current branch
        if: github.ref != 'refs/heads/develop'
        run: |
          git config --global user.email "robot@github.com"
          git config --global user.name "github_robot_user"
          git fetch origin develop:develop --update-head-ok
          git merge develop
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Cache tox envs and pip packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .tox
          key: ${{runner.os}}-${{hashFiles('requirements.txt', 'tox.ini')}}
      - name: Install Tox and Python Packages
        run: pip install tox
      - name: Run Tox
        run: tox
      - name: Prepare Pages
        if: github.ref == 'refs/heads/develop'
        run: |
          mv docs/_build/html/* public/docs
          mv htmlcov/* public/coverage
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: github.ref == 'refs/heads/develop'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          TARGET_FOLDER: .
          CLEAN: true
          SINGLE_COMMIT: true
